language: cpp
compiler: gcc
install:
  - sudo apt-get install yasm libgmp-dev
env:
  global:
    - ENDOMORPHISM=no  BIGNUM=auto    FIELD=auto BUILD=check
  matrix:
    - ENDOMORPHISM=yes BIGNUM=gmp     FIELD=gmp
    - ENDOMORPHISM=no  BIGNUM=gmp     FIELD=gmp
    - ENDOMORPHISM=yes BIGNUM=openssl FIELD=gmp
    - ENDOMORPHISM=no  BIGNUM=openssl FIELD=gmp
    - ENDOMORPHISM=yes BIGNUM=gmp     FIELD=64bit
    - ENDOMORPHISM=no  BIGNUM=gmp     FIELD=64bit
    - ENDOMORPHISM=yes BIGNUM=openssl FIELD=64bit
    - ENDOMORPHISM=no  BIGNUM=openssl FIELD=64bit
    - ENDOMORPHISM=yes BIGNUM=gmp     FIELD=64bit_asm
    - ENDOMORPHISM=no  BIGNUM=gmp     FIELD=64bit_asm
    - ENDOMORPHISM=yes BIGNUM=openssl FIELD=64bit_asm
    - ENDOMORPHISM=no  BIGNUM=openssl FIELD=64bit_asm
    - ENDOMORPHISM=yes BIGNUM=gmp     FIELD=32bit
    - ENDOMORPHISM=no  BIGNUM=gmp     FIELD=32bit
    - ENDOMORPHISM=yes BIGNUM=openssl FIELD=32bit
    - ENDOMORPHISM=no  BIGNUM=openssl FIELD=32bit
    - BUILD=distcheck
before_script: ./autogen.sh
script: ./configure --enable-endomorphism=$ENDOMORPHISM --with-field=$FIELD --with-bignum=$BIGNUM && make -j2 $BUILD
os: linux
